---
title: "Introduction to R: For Biologists and Bioinformatics"
author: |
  | Dr Stevie Pederson
  | Black Ochre Data Labs
  | Telethon Kids Institute
  | 108 North Tce, Adelaide
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Setup (Pre-Workshop)

It is vitally important that your R and Rstudio installations are running before we commence.
Instructions for performing this are available [here]().
Please ensure you have everything installed and running correctly **BEFORE Tuesday 19th September**

Failure to have a working installation prior to the workshop will not only *limit the amount you can learn*, but will also **limit what others can learn** from the session, as we lose time trying to fix your machine.
Importantly, **installing R on a managed device can be unpredictably difficult or easy**.
Please assume you have a difficult device and prepare early.

If you require assistance, we are more than happy to help resolve any issues.
Staff are available to help you with your installation between 2-5pm, Monday 18th September at Telethon Kids Institute, 108 North Tce, Adelaide.
Otherwise, please [email for help](mailto:stephen.pederson@telethonkids.org.au)

If you are unable to get an installation working on your own laptop, please sign-up for a free account at [Posit Cloud](https://posit.cloud/)

## Schedule

Today's workshop will run in 4x90 minute sessions

| Session | Topic | Material | Estimated Duration |
|:------- |:----- |:-------- |:---------------- |
| 9:00 - 10:30  | Introduction            | [Slides](intro_slides.html#/title-slide) | `r round(sum(grepl("^##", readLines(here::here("docs/intro_slides.qmd")))) * 0.5, 0)`min |
|               | What is R and Rstudio   | [Notes](rstudio.html) | `r round(sum(grepl("^##", readLines(here::here("docs/rstudio_slides.qmd")))) * 0.5, 0)`min |
|               | Bringing Data into R    | [Notes](data_import.html) | `r round(sum(grepl("^##", readLines(here::here("docs/import_slides.qmd")))) * 1.5, -1)`min |
| 10:30 - 11:00 | *Morning Tea*           | | |
| 11:00 - 12:30 | Simple Visualisation    | [Notes](basic_ggplot2.html) | `r round(sum(grepl("^##", readLines(here::here("docs/basic_ggplot2_slides.qmd")))) * 1.5, -1)`min |
|               | Working With Text       | [Notes](text.html) | `r round(sum(grepl("^##", readLines(here::here("docs/text_slides.qmd")))) * 1.5, -1)`min |
|               | Spreadsheet-Like Data   | [Notes](tidying_data.html) | `r round(sum(grepl("^##", readLines(here::here("docs/tidying_data_slides.qmd")))) * 1.5, -1)`min  |
| 12:30 - 1:30  | *Lunch*                 | | |
| 1:30 - 3:00   |                         | | |
| 3:00 - 3:30   | *Afternoon Tea*         | | |
| 3:30 - 5:00   |                         | | |

## Required Data

All data for today's session is available [here]().